title: NAS
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
#   - jekyll-tagging
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# # Custom Styles
# custom_css: assets/css/custom.css
defaults:
  - scope:
      path: "" # Applies to all files in the project
    values:
      layout: "default"